language: python
python:
  - "2.7"
before_install:
  - pip install requests
  - python wio_link_execute.py building
install:

script:
  - python helloworld.py
after_success:
  - python wio_link_execute.py success
after_failure:
  - python wio_link_execute.py failure
