language: python
python:
  - "2.7"
before_install:
  - python pion_one_execute.py building
install:
  - pip install requests
script:
  - python helloworld.py
after_success:
  - python pion_one_execute.py success
after_fail:
  - python pion_one_execute.py fail
