language: python
python:
  - "2.7"
# command to install dependencies
install:
# command to run tests
script:
  - python helloworld_simple.py
notifications:
  email:
    - teng.wang@seeed.cc
  webhook:
    - https://maker.ifttt.com/trigger/build_success/with/key/pgefcJnXQwOoRZlUztoX1
