language: python
python:
  - "2.7"
before_install:
  - pip install requests
  - python pion_one_execute.py building
install:

script:
  - python helloworld.py
after_success:
  - python pion_one_execute.py success
after_failure:
  - python pion_one_execute.py failure
